# Generated by Django 4.2.2 on 2024-10-02 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите связаную привычку",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_habits",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
