# Generated by Django 4.2.2 on 2024-10-04 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_related_habit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"verbose_name": "Привычка", "verbose_name_plural": "Привычки"},
        ),
        migrations.AddField(
            model_name="habit",
            name="first_habit_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата и время первого выполнения привычки",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="habit",
            name="next_habit_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время следующего выполнения привычки",
            ),
        ),
    ]
